
development:
  host: ec2-54-217-213-79.eu-west-1.compute.amazonaws.com
  adapter: postgresql
  encoding: unicode
  database: dd7n1hmp0e8eie
  username: okhpbsvmmiials
  password: ded8386c3b3289c3c0311255addfe87dd0f29374b7a01f61a881890459c4ca44
  pool: 5
  timeout: 5000


test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: echogramlib
  username: postgres
  password: miao
  pool: 5
  timeout: 5000

production:
  host: ec2-18-210-51-239.compute-1.amazonaws.com
  adapter: postgresql
  encoding: unicode
  database: echogramlib
  username: postgres
  password: miao
  pool: 5
  timeout: 5000
